api/urls.py, api/views.py
I was unable to fetch non-human proteins of a family. 
* Removed Homo sapiens filter on `/proteinfamily/proteins/{slug}` endpoint.
* Created an additional endpoint to return proteins belonging to one family and one species.
Now to get only human proteins of a family use `/proteinfamily/proteins/001_001_001/Homo&20sapiens`.
=> Proteins of family from all species or a single selected species.

construct/views.py
Wild type calculations were being performed on the mutant amino acid, not the wild type amino acid.  This is now fixed.
=> Correct wildtype grouping calculations

api/views.py
Similarity comparison didn't work anymore, which also affected the 3D-e-Chem GPCRdb KNIME nodes.
=> Fix for fatal error web services similarity function

common/alignment.py, protein/models.py, signprot/templates/signprot/coupling_browser.html, signprot/views.py, static/home/css/signprot-multitabtable.css, static/home/js/signprot-multitabtable.js
- Note on models for protein-gprotein table.
- Frontend: table headers for signprot/couplings families table
invisible columns for coupling classification
- Prepare views.py for classification criteria using all data.
- reset_tab hash fix
- DataTables filter_container_id trick to add additional filter where needed while hidding the corresponding colums. trick thanks to C. Munk.
=> UPDATE: Droplist with filter for Gprotein-GPCR coupling classification

home/templates/home/index_gpcr.html, pages/urls.py, pages/views.py, static/home/css/style.css
- Link to statistics page in index page.
- Change blue border to rgba with transparent property
- Cleanup odd all-embedding in html row.
- Refactor views in the *pages* app to Django 3.
Just a reminder that the *url* function is in a path to deprecation.
Still works as it has been made into an alias of django.urls.re_path(),
but better to use ```from django.urls import path.```
=> UPDATE: Minor changes. Link to stats in main page, clean html.

api/views.py
Fix for the PDB residue numbering API. In a request from a "rest_framework" direct access to request.FILES is not allowed anymore + would throw a "django.utils.datastructures.MultiValueDictKeyError" + "Request should include a Content-Disposition header with a filename parameter." error.
See: https://www.django-rest-framework.org/api-guide/requests/#data
=> FIX: direct access to FILES in REST framework request

common/templates/common/selection_buttons.html, common/urls.py, common/views.py, phylogenetic_trees/views.py, static/home/js/selection.js
Implemented generic function to verify if the selected receptors (can be extended to other selection types) meet a specific cutoff. If not, the user is presented with a notification before continuing.
This is now implemented for just the phylogenetic tree functionality where the select of at least 3 receptors is required to generate a tree. We could consider adding this to all receptor pages with a minimum of 1.
=> UPDATE: verification of selected # receptors before continuation

alignment/templates/alignment/alignment.html, seqsign/templates/sequence_signature.html, static/home/css/alignment.css, static/home/js/alignment.js
Sticky top scrollbar on alignment and seq. sign. pages
* The upper scrollbar is now visible in all browsers (before only Chrome). 
Note: width calculation was performed before making the table contents visible.
* The upper scrollbar stays visible even when scrolling vertically (sticky on top) - tested for Firefox/Safari/Chrome/Edge
Sequence Signature tool:
* Faster loading by starting with hidden table
* Same changes as for alignment pages (scrollbar + cross-browser fix)
* Made the applyCutoff call unique to SeqSign page - no need to run it on alignment page
=> UPDATE: sticky scrollbar aligns + performance drawing SeqSign + cleanup

drugs/templates/drugbrowser.html, drugs/templates/drugmapping.html, interaction/templates/interaction/structure.html, ligand/templates/BiasedBrowserBackEnd.html, ligand/templates/bias_browser.html, ligand/templates/bias_browser_g.html, protein/views.py, seqsign/sequence_signature.py, signprot/templates/signprot/gprotein.html, static/home/css/style.css, structure/views.py
* Removal of consensus sequences from search hits (prevent error)
* Adding full alias search for search box
* Removal redundant references that are replaced by "Cite us" tool
* Fix for embedded table cells and NaN links in drug browser
* Redirecting PDB searches to structure table
* Cleanup: removal PoseView promise, redundant references
* Menu-bar is more flexible/responsive to screen size in order to prevent two lines if possible
* removal redundant CSS that broke the menu bar in statistics page
* Fix for handling missing segments in seq. sign. tool (e.g. ICL1)
Note: ugly rebase, so timestamps of the commits are off
=> Series of smaller fixes for the October release

common/views.py, static/home/js/targetselect_functions.js
Two fixes for the receptor selection table
- HTML setting for proper handling of html data in UniProt column (due to UniProt links)
- Quick fix for handling a circular dependency when building - TODO - move table initialization
=> Double quick fix for receptor selection table

structure/templates/model_statistics.html
At times some "magic" corrects the missing two double slashes after the colon, but not always.
And while at it http to https.
=> FIX: Just two missing slashes.

api/views.py, construct/tool.py, interaction/views.py, mutation/views.py, protein/views.py, signprot/views.py
* Handling of proteins without directly-associated genes
* Improved handling of queries for GPCRs to the signprot detail page
* Workaround for multiple signaling entities in a single signaling protein structure
* Redirect to selection page for the mutation browser for unknown proteins
* Handling non-sequence generic number matching for interactions
* Fixed API alignment issue to empty line handling
* Construct tool - handling data request for receptor without structure
=> Another batch of January release fixes

alignment/templates/alignment/alignment_fasta.html, signprot/views.py, structure/assign_generic_numbers_gpcr.py
* All GPCR classes instead of only class A redirect to their own page for Signprot detail page views for GPCRs
* Removal of empty line at start of Fasta download
* Improved fix for renumbering of non-numerical segments
=> Three quick fixes

residue/templates/residue/residue_table_only.html, residue/templates/residue_table.html, residue/views.py
_Minor adjustments_:
- Generic residue number tables (receptors, g proteins, arrestins) have been visually updated
- segment name now is highlighted (lightgrey) and centered
- added sticky css for headers
- modified context values in the view and added variables 
- switched internal if/else in the view to external one to comply with header changes
=> LAYOUT: update Generic Residue Number tables layout

residue/templates/residue/residue_table_only.html, residue/views.py
_Minor adjustments:_
- generic residue number table for G proteins and Arrestins now has header horizontal in two lines (protein / specie)
- removed unused headlines for mutations
- adjusted table to fix visualization only for G protein table and Arrestins and not in receptor (still has oblique header)
=> LAYOUT: adjusted two lines header, removed unused headliner

residue/templates/residue/residue_table_only.html, residue/views.py
_Minor layout updates:_
- Changed "Common residue number" into "Generic residue number" (Gprot & Arrestins table)
- Added subscript pattern to Gprot headers after the capital G
- Removed brackets around specie/s
- Adjusted th **row-header** class
- Updated Receptor table to be consistent with Gprot and Arrestins (horizontal sticky header)
- Added replacements for receptor names for Receptor table in view (receptor/adrenoceptor/olfactory ecc)
- Cherry picked commit from Albert (hotfix)
=> LAYOUT: yamu (yet another minor update) on table headings (Gprot/Arr)

interaction/views.py, ligand/views.py, mutation/views.py, signprot/templates/signprot/coupling_profiles.html
_Minor bugfix_:
- Fixed issue in the mutation selection page that provided an error when all mutations were removed after selection of the receptor (empty https://gpcrdb.org/mutations/segmentselection page). Now redirects to Mutations select table (https://gpcrdb.org/mutations/);
- Fixed issue in ligand selection page that resulted in not having any ligand selected, raising an error for a variable called but not assigned (empty call). Now redirects to the ligand selection page (ligand_browser);
- Fixed issue in empty downloading in the interaction/download page when nothing is cached. Added a try/except that redirects to /interaction/ when failing to properly function.
**Error messages fixed:**
StructureLigandInteraction   matching query does not exist  --> interaction/download …
=> List of bugfix from May 2021 logs

build/management/commands/build_citations.py, build/management/commands/build_g_protein_structures.py, build/management/commands/build_g_proteins.py, build/management/commands/build_mutant_data.py, build/management/commands/build_structures.py, common/models.py, structure/management/commands/new_xtals.py, tools/management/commands/upload_excel_bias.py, tools/management/commands/upload_excel_bias_pathways.py
This PR tries to address duplication of publications and journal, inconsistent journal abbreviations and code duplication.
- Slugs were generated in multiple ways based on journal abbreviations
- Corrected the handling of CrossRef journal abbreviations
- Journal and slug matching are now case insensitive
- CrossRef was main for DOI, but Entrez for PMID resulting different journal abbreviations - Entrez is now main for both with PMID as backup
- Generalized functions now provide a cleaner way of retrieving or creating a publication - less code
Note: due the existing duplications, running a build script on an existing database will give you fatal errors. 🤞 for the full new build
=> UPDATE: new functions for PMID and DOI matching

common/alignment.py
The comments of the blocks of code handling similarity and identity in calculate_similarity_matrix() of alignment.py are switched around.
pairwise_similarity() returns a tupple = (identity, similarity, similarity_score), so calc_values[1].strip() is similarity and calc_values[0].strip() is identity.
=> fix comments in calculate_similarity_matrix method of alignment class

ligand/templates/endogenous_browser.html
There was an issue with the Endogenous Browser filtering columns. 
Now both UniProt and IUPHAR column filter should be working.
=> FIX: Filtering columns fixed in endogenous_browser
