- build/management/commands/build_structures.py
- common/models.py
- structure/assign_generic_numbers_gpcr.py
- structure/functions.py
Another way of building residues for structures. Build from PDB files and get GN from blasting. Please review and comment.
> Changed to build_structures.

- api/serializers.py
Forgot to add fold change to mutants api
Added date is not part of Excel template used for submission, so removed it from api.
> Added fold change to mutants api, removed added date from mutants api.

- build/management/commands/build_residue_sets.py
- common/selection.py
- common/templates/common/selection_filters_gproteins.html
- common/templates/common/selection_filters_gproteins_selector.html
- common/templates/common/selection_filters_pref_gproteins.html
- common/templates/common/selection_filters_pref_gproteins_selector.html
- common/templates/common/selection_lists.html
- common/templates/common/selection_segments.html
- common/templates/common/targetselection.html
- common/views.py
- sitesearch/views.py
- static/home/js/selection-filters.js
- static/home/js/selection.js
removed openpyxl requirement
implemented David's remarks
> Receptor filtering updates

- structure/management/commands/list_new_xtals.py
> list_new_xtals script. Lists GPCR xtals that are not yet in your version of GPCRdb

- api/urls.py
- api/views.py
- build/management/commands/build_mutant_data.py
- build/management/commands/build_parse_construct_structures.py
- build/management/commands/build_prepare_new_structures.py
- build_gpcr/management/commands/build_parse_construct_structures.py
- home/templates/home/mainmenu_gpcr.html
- mutation/templates/mutation/statistics.html
- structure/functions.py
- structure/sequence_parser.py
- structure/templates/structure_browser.html
- tools/management/commands/sequence_parser.py
Sequence parser for constructs. 
First implementation of the REST service for sequence parser.
> Sequence parser

- static/home/js/statistics_diagram_crystals.js
- structure/templates/structure_statistics.html
- structure/views.py
Two tables with stats, update to counting of the receptors and an additional phylo tree of the crystal structures.
> Update to the stats page

- ligand/templates/ligand_browser.html
- ligand/templates/ligand_details.html
- ligand/templates/ligand_statistics.html
- ligand/templates/target_details.html
- ligand/templates/target_details_compact.html
- ligand/templates/target_purchasability_details.html
- ligand/urls.py
- ligand/views.py
- static/home/css/ligand_browser.css
- static/home/js/phylo_tree.js
- structure/templates/structure_statistics.html
- structure/views.py
Reworked into 4 browser subpages. Purchasability does not preserve ligand selection
> Ligand browser

- ligand/templates/ligand_browser.html
- ligand/templates/target_details.html
- ligand/templates/target_details_compact.html
- ligand/templates/target_purchasability_details.html
- ligand/views.py
> Updates to ligand browser

- alignment/templates/sequence_signature/sequence_signature_bckup.html
- alignment/templates/sequence_signature/signature_aln_neg_left_panel.html
- alignment/templates/sequence_signature/signature_aln_pos_left_panel.html
- alignment/templates/sequence_signature/signature_left_panel.html
- common/sequence_signature.py
- use negative values in the property consensus
- renamed features to properties, etc. (David's request)
> Bugfix for property consensus and small cosmetic changes to the layout.

- mutational_landscape/views.py
These changes fix the current issues with the mutational landscape pages.
> Fixes mutational landscape pages

- api/urls.py
- api/views.py
- common/alignment.py
A second round of optimizations to reduce load + memory bottlenecks
> Hotfix: memory and DB killers

- home/templates/home/index_gpcr.html
- home/templates/home/mainmenu_gpcr.html
- protwis/settings.py
- protwis/settings_local_development.py
- protwis/settings_local_production.py
- signprot/templates/signprot/browser.html
- signprot/views.py
> Let's try again

- signprot/templates/signprot/browser.html
Just change hex color to something a little bit darker and revert
to correct String match.
> FIX: Revert to correct String and change hex color.

- build/management/commands/build_g_proteins.py
- signprot/templates/signprot/browser.html
- signprot/views.py
Minor changes in protein coupling tables format.
Reverted commenting out in the data importer build_g_proteins.py
> UPDATE: Continuing changes in tabs for protein coupling.

- static/home/js/contactbrowser-tm7.js
- static/home/js/contactnetwork-downloads.js
Now it works for both HTML and SVG :-)
> Updated fix for SVG

- build/management/commands/build_g_proteins.py
- protein/models.py
- signprot/views.py
A corresponding 200127_bouvier.xlsx is in the gpcrdb_data
repository, this merge depends on that one being done prior.
The missing data needed by the frontend can be injected now using
the build_g_proteins module.
> UPDATE: Import data from Bouvier and Hauser into database.

- build/management/commands/build_all.py
- ligand/templates/ligand_statistics.html
- ligand/views.py
- mutation/templates/mutation/statistics.html
- mutation/views.py
- structure/templates/structure_statistics.html
- structure/views.py
- tools/management/commands/build_structure_angles.py
Small addition is automatically setting the parallel workers for the build_structure_angles
> Fixes for renaming class T

- api/views.py
- common/templates/common/tree_options.html
- home/templates/home/500_gpcr.html
- home/templates/home/mainmenu_gpcr.html
- ligand/views.py
- static/home/css/structure_browser.css
Mostly reorganizing the menu system and some small tweaks.
> Mostly reorganizing the menu system and some small tweaks

- build/management/commands/build_structures.py
- construct/functions.py
Adding exceptions and fixes for structure handling
> Structure build bug fixes

- home/templates/home/index_gpcr.html
Minor changes in main page presentation.
> UPDATE: Move blocks around in main page and make links to cite-us

- home/templates/home/mainmenu_gpcr.html
- ligand/templates/ligand_statistics.html
- phylogenetic_trees/templates/phylogenetic_trees/phylo_tree.html
- static/home/css/modal.css
- static/home/js/citation_tool.js
- static/home/js/joinus_tool.js
- static/home/js/phylotree.js
New join-us tool + menu layout
> New join-us tool + menu layout

- home/templates/home/index_gpcr.html
David asks for adding a direct link to GPCRmd.
> UPDATE: Add link to index page.

- home/templates/home/mainmenu_gpcr.html
Some few place changes for menu system and rename External GPCR servers
to External GPCR sites, which comes with the according change in the
gpcr_data repo which holds the sphinx link to readthedocs.
> UPDATE: Requests from David Gloriam on menu system.

- home/templates/home/mainmenu_gpcr.html
Put back biased signalling as requested by David.
> UPDATE: Minor changes to mainmenu

- home/templates/home/index_gpcr.html
- home/views.py
Few changes on where things are placed at index_gpcr
and some rewording.
> UPDATE: More changes on David's requirement for index_gpcr

- home/templates/home/index_gpcr.html
- home/templates/home/mainmenu_gpcr.html
Minor mainmenu and index page changes.
> UPDATE: More mainmenu minor changes

- home/templates/home/index_gpcr.html
- home/templates/home/mainmenu_gpcr.html
New links.
Upload new overview.pdf and gpcrdb video by DEG.
> UPDATE: Latest changes requested by DEG

- home/templates/home/base.html
- ligand/templates/ligand_browser.html
- static/home/css/modal.css
- static/home/css/style.css
First commit - adding a general alert JS function for all pages (base template)
Second commit - handling the absence of a receptor selection for the ligand browser
> Handling alerts generally and handling a missing selection

- interaction/templates/interaction/interactionselection.html
- interaction/views.py
Title says it all.
Note: also removed PDB upload - due to issues with PDB annotation (see #174)
> LAYOUT: removing manual input + added multi-level select for structure

- build/management/commands/build_g_protein_structures.py
- construct/functions.py
- structure/functions.py
- structure/management/commands/structure_anomaly_recognition.py
- structure/templates/g_protein_structure_browser.html
- structure/templates/structure_browser.html
> Structure build update part 2

- common/alignment.py
- protein/views.py
* The protein segment selection for the isoforms table was not correct anymore (due to new D1 segments) and therefore the isoforms page/table wasn't correctly functioning anymore + layout was off
* Disabling the empty segments removal in the alignment code as it resulted in a errors in some cases
> Code fixes

- alignment/views.py
- common/diagrams_gpcr.py
- construct/templates/new_tool.html
- construct/views.py
- protein/templates/protein/sequence_viewer.html
- static/home/js/diagrams.js
- tools/management/commands/assign_structure_states.py
This PR addresses the issues described in three PRs (#218 , #219 and #221 ).
In addition it updates the state/degree active values for the latest release. Next time this should of course be done before the actual release.
> Multiple issue fixes and updating the states/degree active

- common/views.py
- residue/views.py
* Fixing server errors for "residue number table"
* Fixing default generic numbering scheme selection
> Minor fixes for the next release

- signprot/templates/signprot/family_details.html
- signprot/templates/signprot/signprot_details.html
> FIX: corrected link to g protein structure browser

- alignment/views.py
- build/management/commands/build_structures.py
- common/templates/common/selection_table.html
- common/templates/common/selection_tree.html
- common/templates/common/targetselectiontable.html
- common/views.py
- interaction/legacy_functions.py
- interaction/views.py
- static/home/css/bootstrap-responsive.css
- static/home/css/phylo.css
- static/home/css/select2.css
- static/home/css/spectrum.css
- static/home/css/style.css
- static/home/css/targetselect_functions.css
- static/home/js/contactbrowser-tabtables.js
- static/home/js/targetselect_functions.js
- tools/management/commands/assign_structure_states.py
- tools/management/commands/upload_excel_bias_pathways.py
The good, a new functionality matching this branch:
* New table-based target selection page
The bad, updates not related to this functionality:
* Updated structure state assignment
* Added maximum AA conservation column for structural comparisons
The ugly, some fixes that crept in:
* Added missing purge functionality for pathways
* Solved Excel interaction download error
Next up: awaiting the Codacy analysis and then adding a commit improving the code style
> Implementation of the target selection page with table + few hot fixes

- alignment/views.py
- common/templates/common/selection_table.html
- common/templates/common/targetselectiontable.html
- common/views.py
- contactnetwork/views.py
- static/home/css/jquery.dataTables.yadcf.css
- static/home/css/style.css
- static/home/js/matrix_utilities.js
- static/home/js/targetselect_functions.js
* Updated table target browser (layout + new columns + link-outs)
* Replaced hardcoded alerts with soft alerts for interface browser
* Bit of code cleaning (more to be expected)
> Updated target table browser

- common/views.py
- ligand/views.py
- static/home/css/style.css
- static/home/js/targetselect_functions.js
* Enabled slug-based ligand page
* Added ligand count column
* Adjusted layout
* Adjusted link types in table
> Update for target search page

- build/management/commands/build_release_notes.py
- home/templates/home/index_gpcr.html
- home/templates/home/mainmenu_gpcr.html
- home/views.py
- signprot/templates/signprot/gprotein.html
- tools/management/commands/assign_structure_states.py
- Updated menu system
- Updated main page release statistics
- Updated coupling page
- Adjusted state cutoffs for the new structures
> Set of updates for December release

- mutation/views.py
- mutational_landscape/views.py
- phylogenetic_trees/views.py
- seqsign/views.py
- similaritymatrix/views.py
- similaritysearch/views.py
- sitesearch/views.py
- static/home/js/targetselect_functions.js
Enabling the new receptor selection page for:
* Alignments
* Phylogenetic trees
* Genetic variants
* Sitesearch
* Sequence signatures
* Similarity search
* Similarity matrix
+ adding a minimum selection check
> UPDATE: enabling new receptor selection page for different tools

- alignment/templates/alignment/alignment_fasta.html
- alignment/templatetags/alignment_extras.py
> FIX: quickfix for fasta issue (fix #268)

- alignment/templates/alignment/alignment_fasta.html
- alignment/templatetags/alignment_extras.py
- build/management/commands/build_release_notes.py
- common/definitions.py
- common/diagrams_gpcr.py
- common/templates/common/selection_buttons.html
- common/templates/common/targetselection.html
- home/templates/home/mainmenu_gpcr.html
- home/views.py
- interaction/views.py
- mutation/templates/mutation/contact_mutation_design.html
- mutation/templates/mutation/gprot_mutation_design.html
- mutation/urls.py
- mutation/views.py
- seqsign/sequence_signature.py
- static/home/css/style.css
- static/home/js/contactbrowser_functions.js
- static/home/js/grayscale.js
- tools/management/commands/assign_structure_states.py
- Couple of bug fixes
- Updated release statistics
- Updated menu system
- Tweaked the grayscaling function with 2/3 color gradients, negative value and absolute value coloring
- Implementations + updates of the pending "State-stabilizing mutation design tool"
- Implementations + updates of the pending "Coupling determinant mutation design tool"
> January update + design tools

- common/diagrams_gpcr.py
- mutation/views.py
- Fixes duplicated ECL1 / D1e1 in STE2 snakeplot
- Fixes wrong call to generate consensus snakeplot
- Fixes the previous fix to handle the wrong snakeplot call
> FIX: Class D1 issues

- common/views.py
- construct/views.py
- static/home/js/targetselect_functions.js
- Handling exception for classes without annotated truncations for the Truncation and Fusion analysis tools
- Handling selection of non-human targets in the receptor selection table
> Another two fixes for January release

- build/management/commands/build_g_proteins.py
Just a change of source names.
> UPDATE: Fix names in sources.

- signprot/templates/signprot/coupling_browser.html
- static/home/js/signprot-multitabtable.js
- Set ordering to be Mean first, then alphabetic.
- Rephrasing accoding to todo.
> UPDATE: Minor rephrasing requirements and ordering.

- signprot/views.py
- static/home/css/signprot-multitabtable.css
- static/home/js/signprot-multitabtable.js
- Over counting on make_range_number_cols
- Fix ordering also in subtypes tab.
- Round to one decimal.
> FIX: Bad counting on make_range_number_cols.

- build/management/commands/build_homology_models.py
- build/management/commands/build_release_notes.py
- structure/templates/homology_models.html
- structure/views.py
- tools/management/commands/assign_structure_states.py
- Fix for complex homology models
- Adjusted state assignment cutoffs based on new structures
- Added skip existing models option to hom. model building script
- Temp. added refined complex count to release stats
> Couple of fixes and updates for the March release

- build/management/commands/build_arrestins.py
- build/management/commands/build_g_proteins.py
Previously on purge the primary id key was restarted with one using
a direct SQL call, now using sequence_reset_sql
Thanks to AJK-dev for the tip.
> OPTIMIZE: Change direct SQL call to Djangonic sequence_reset_sql

- residue/templates/residue/residue_table_only.html
- residue/views.py
_Bugfixes:_
- Adjusted row-header length to match all columns when multiple numbering schemes are selected (Receptors)
- Fixed bug while downloading excel tables from Arrestins or GProt numbering tables
> FIX: fixed download for Gprot/Arr tables

- signprot/templates/signprot/coupling_browser.html
- static/home/js/gpcrdb.js
- static/home/js/signprot-multitabtable.js
- Following TODO adding Group and Biosensor colums in the source
category.
- Move select_all and copyToClipboard functions to gpcrdb.js
> UPDATE: Group and Biosensor columns.

- ligand/templates/ligand_statistics.html
- ligand/views.py
- static/home/js/phylo_tree.js
**Major updates:**
- updated function for color shading in js (now applies to all colors rather than only gray)
**Minor updates:**
- updated IUPHAR names (now capitalized where missing)
- updated external circles visualization (now every circle has a different color fill)
- updated wording across the page
- removed Class D1 from ligand table
> Ligand Bias Statistics page update

- structure/templates/structure_statistics.html
_Minor updates_:
- Updated title for second table in the page (according to ToDos request)
- Removed placeholder text
- Fixed {% if %} positioning to hide barplot graph from Receptor/Structure_Statistics
> G Protein structure statistics page revision

- api/urls.py
- api/views.py
- build/management/commands/build_release_notes.py
- common/alignment.py
- home/templates/home/index_gpcr.html
- home/templates/home/mainmenu_gpcr.html
- home/views.py
- signprot/templates/signprot/matrix.html
- signprot/templates/signprot/signature_match.html
- signprot/views.py
- static/home/css/style.css
- static/home/js/fixed_columns.js
- static/home/js/signprotmat.js
- static/home/js/targetselect_functions.js
- Fixed bug in sequence signatures for residue sets (seq. sig. tool, alignment tool, receptor-Grot interface profile)
- Updated menu system
- Adjusted statistics page
- Support for selection page for import of full UniProt IDs with species
- Updated API documentation
- New API call to include TrEMBL sequences
- Fixed species-specific sequence alignment call
- Code cleanup
> First set of updates for May build

- build/management/commands/build_consensus_sequences.py
Issue when using multiple parallel processes, especially in combination with short tasks. The higher the number of processes and the shorter the tasks, the higher the chance that this will occur.
In this case, it can happen that in the time between checking if there is work and obtaining the lock, another process has already grabbed this work. So after obtaining the lock, another check is necessary to find out it there is still work to be done or not.
TODO for all: check rest of code for similar situations
> FIX: extra check condition when parallel processing after obtaining lock

- build/management/commands/build_release_notes.py
- home/templates/home/index_gpcr.html
- home/views.py
- static/home/css/style.css
- structure/templates/homology_models.html
Minor updates:
* Updated homology model download
* Adjusted GPCRdb stats layout and release_notes build
> Build updates for June

- contactnetwork/templates/contactnetwork/clustering.html
- contactnetwork/views.py
- home/templates/home/base.html
- home/templates/home/mainmenu_gpcr.html
- home/templatetags/mainmenu.py
- mutation/templates/mutation/contact_mutation_design.html
- mutation/views.py
- protein/views.py
- protwis/context_processors.py
- protwis/settings.py
- static/home/js/fixed_columns.js
- static/home/js/structure_browser.js
- static/home/js/structures_clustering.js
- static/home/js/targetselect_functions.js
- Updated state-stabilizing mutation design tool to state-affecting mutation design tool
- Minor fix: handling "back button" behavior for the table selection tool
- Minor update: added "allosteric agonist" to the modalities list of the structure browser (in-line with updated annotation in gpcrdb_data)
- Fixing selection panel for ligand mutation design tool - max of 1 target
- Fixing ligand functionality annotations for structural similarity tool
- New effector protein addition for the structural similarity tool
- Search box fix - no PDBs unless doing a "navbar" search
- Added domain check/control to the context for handling within the templates
> Mixed updates

- structure/templates/homology_models.html
- tools/management/commands/assign_structure_states.py
- Adjusted activation state cutoffs for class A and C
- Added homology model download for July-21
> Updates for July build

- contactnetwork/views.py
- static/home/css/style.css
- structure/templates/structure_browser.html
* Updated links to documentation
* Small CSS fix breaking header when header width between 1400-1600 pixels
> Minor updates

- build/management/commands/build_all.py
- build/management/commands/build_coupling_data.py
- build/management/commands/build_g_proteins.py
- build_gpcr/management/commands/build_coupling_data.py
* Split up building couplings and G proteins (simplifies and corrects for missing arrestins)
> August build fixes

- build/management/commands/build_blast_database.py
- build/management/commands/build_construct_data.py
- build/management/commands/build_dynamine_annotation.py
- build/management/commands/build_residue_sets.py
- common/views.py
- construct/functions.py
- home/templates/home/base.html
- interaction/views.py
- signprot/interactions.py
- signprot/templates/signprot/coupling_browser.html
- signprot/templates/signprot/coupling_profiles.html
- signprot/urls.py
- signprot/views.py
- sitesearch/views.py
- static/home/css/signprot-multitabtable.css
- static/home/js/arrestin_coupling.js
- static/home/js/gpcrdb.js
- static/home/js/gprotein_coupling.js
- static/home/js/matrix_utilities.js
- static/home/js/signprot-multitabtable.js
- structure/assign_generic_numbers_gpcr.py
- structure/templates/homology_models.html
- tools/management/commands/assign_structure_states.py
- tools/management/commands/blast_recent_PDB.py
- tools/management/commands/build_bias_data.py
- tools/management/commands/upload_excel_bias.py
* Small overhaul of the coupling browsers including performance increase + code cleanup
* Added generalized function to GPCRdb.js incl. YADCF filter creation
* New function to perform a 7TM BLAST against the RCSB PDB for identification of new structures
* Added caching to the dynamine predictions
* Updated cut-offs and settings for activation state
* Fix coupling statistics pages
* Fix interface interaction & profiler (interface matrix) - enabled new GtP coupling data + disabled old toggling options
* Fix G interface page (although deprecated - will be removed in one of the next builds)
* Fix for soon to be deprecated bias upload and build
* Fix to make dynamine residue data building a parallel safe function
* Added a purge function for construct data building
* Codacy code styling issues …
> Collection of updates and fixes for August build

- common/templates/common/selection_buttons.html
- common/templates/common/selection_table.html
- common/views.py
- ligand/templates/biased_rank_orders.html
- ligand/templates/ligand_statistics.html
- ligand/views.py
- static/home/js/phylo_tree.js
- static/home/js/referenceselect_functions.js
_Minor updates:_
- updated layout of "_Biased Statistics_" pages, adding tab panels for further updates;
- updated all browser pages, with new column (balanced references) in the table and new buttons, for further updates;
- updated browser page structure when missing family tree and species selection;
- added modals, added mockup function for further development
> Biased signalling pages update

- signprot/templates/signprot/coupling_browser.html
- static/home/js/arrestin_coupling.js
- static/home/js/gprotein_coupling.js
- static/home/js/matrix_utilities.js
- static/home/js/signprotmat.js
* Quicker loading of coupling pages by hiding the table while building
* Fix for issue #383 - corrected outline residue and property conservation + added interaction conservation
> Fixes for current build

- contactnetwork/views.py
- static/home/js/structures_clustering.js
Updated the code to identify GRK structures and process them in the structure similarity trees.
> FIX: annotation of GRK structures for structural similarity trees

- build/management/commands/build_all.py
- build/management/commands/build_structures.py
- structure/functions.py
- structure/management/commands/new_xtals.py
- structure/templatetags/structure_extras.py
I'm still working on the new_xtals script, for now I just disabled the creation of yaml files
> HOTFIX: minor fixes

- common/views.py
- contactnetwork/views.py
- structure/functions.py
- structure/structural_superposition.py
Hotfix for structure GNs (closes #440)
> HOTFIX: struct comp tool and superpositions

- api/urls.py
- api/views.py
- common/templates/common/selection_ligand_name.html
- home/templates/home/gpcrdb.html
- ligand/templates/ligand_info.html
- ligand/templates/ligand_name_selection.html
- ligand/templates/otf_biased_rank_orders.html
- ligand/templates/target_details.html
- ligand/urls.py
- ligand/views.py
- protein/views.py
- protwis/settings.py
- static/home/css/style.css
- static/home/js/dotPlot_jitter.js
- static/home/js/selection-autocomplete.js
- structure/templates/structure_browser.html
Hello and welcome to this mini PR!
Below, a list of the small changes featured in the update:
**- Major Changes:**
- Ligand Browser query based on ligand name, SMILES or database ID (GtP, Chembl, DrugCentral)
_- Minor Changes:_
- Updated tooltips in the Bias Ranking scatter plots (now more info and corrected design/numbering)
- Cleaned redundant code in html pages and js scripts
- Added potency and affinity tabs in Ligand Info pages
- Fixed wrong behaviour for triangles in Scatter Plots
- Column renaming in Ligand Browser
- Right aligned numbers in Data Box (all landing pages)
- Adjusted info in Structure Browser
> NAR Proofs update

- api/serializers.py
- api/urls.py
- api/views.py
- build/management/commands/build_mutant_data.py
- home/templates/home/cite_gpcrdb.html
- home/templates/home/index_gpcr.html
- ligand/urls.py
- ligand/views.py
- mutation/models.py
- static/home/js/citation_tool.js
- static/home/js/joinus_tool.js
Hello and welcome to this small PR!
Below a list of the changes featured:
_Minor Changes:_
- Added links to documentation in the carousel images
- Adjusted syntax in the GPCR citing page
- Implemented a redirect linkage for Guide to Pharmacology ligand to show related GPCRdb ligand info page
- Implemented API call for retrieving all available ligands with a Guide to Pharmacology ID
- Fixed Mutation build, adjusting FoldChange calculation and data visualization in Mutant browser
> Guide to Pharmacology tunnel & updates

- home/templates/home/index_biasedsignalingatlas.html
The main article for A community Biased Signaling Atlas is finally out in Nature Chemical Biology!
We have a banner to celebrate this milestone!
> UPDATE: BSA article out cheer banner

- api/serializers.py
- api/urls.py
- api/views.py
> UPDATE: added complex interaction to api

- build/management/commands/build_coupling_data.py
- home/templates/home/index_biasedsignalingatlas.html
- signprot/templates/signprot/coupling_browser.html
- signprot/templates/signprot/coupling_profiles.html
- signprot/templatetags/coupling_extras.py
- signprot/views.py
- static/home/css/signprot-multitabtable.css
- static/home/js/gprotein_coupling_families.js
Coupling browser
- GproteinDb rows
- GtoPdb rows
- updated reference layout
Other minor fixes
> UPDATE: Coupling browser update

- static/home/js/fixed_columns.js
- static/home/js/gpcrdb.js
Fixes:
Multiple References Formatting: References are now displayed with appropriate line breaks.
Ligand List Enhancements: Multiple ligands are now separated by line breaks, ensuring a cleaner and more organized presentation.
Simplified Ligand Names: Display of ligands has been simplified to show just the ligand name, removing unnecessary details for a more streamlined view.
Direct Links to Refined Structures: Added direct links to refined structures for each ligand, providing easy access to more detailed information.
> FIXED: GlobalToExcel function

- static/home/js/joinus_tool.js
Fixed a typo and updated Twitter reference to X.
> Typo and update joinus_tool.js

- build/management/commands/build_human_proteins.py
- build/management/commands/build_structures.py
- build/management/commands/split_uniprot_file.py
- structure/functions.py
- structure/management/commands/add_annotation.py
- structure/management/commands/download_from_alphafolddb.py
- add_annotation extended to run on receptors not in db yet (e.g. odorants)
- update needed to biopython 1.81
- automated download from AlphaFolddb script
> UPDATE: odorant receptors related update

- build/management/commands/build_all.py
- build/management/commands/build_receptor_similarity.py
> UPDATE: Build receptor similarity
